USE [master]
GO

/****** Object:  Database [rent_a_car_Dev]    Script Date: 16-Jul-20 14:30:20 ******/
CREATE DATABASE [rent_a_car_Dev]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'rent_a_car_Dev', FILENAME = N'C:\Users\Luka\rent_a_car_Dev.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'rent_a_car_Dev_log', FILENAME = N'C:\Users\Luka\rent_a_car_Dev_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [rent_a_car_Dev].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [rent_a_car_Dev] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET ARITHABORT OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [rent_a_car_Dev] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [rent_a_car_Dev] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET  DISABLE_BROKER 
GO

ALTER DATABASE [rent_a_car_Dev] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [rent_a_car_Dev] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [rent_a_car_Dev] SET  MULTI_USER 
GO

ALTER DATABASE [rent_a_car_Dev] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [rent_a_car_Dev] SET DB_CHAINING OFF 
GO

ALTER DATABASE [rent_a_car_Dev] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [rent_a_car_Dev] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [rent_a_car_Dev] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [rent_a_car_Dev] SET QUERY_STORE = OFF
GO

USE [rent_a_car_Dev]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [rent_a_car_Dev] SET  READ_WRITE 
GO

